CREATE TABLE IF NOT EXISTS investment (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	created_at DEFAULT CURRENT_TIMESTAMP,
	updated_at DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portfolio (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	entry_time DATE DEFAULT CURRENT_DATE,
	balance INTEGER DEFAULT 0,
	investments JSON
);

CREATE INDEX idx_entry_time ON portfolio (entry_time);
