CREATE TABLE IF NOT EXISTS investments (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	created_at DEFAULT CURRENT_TIMESTAMP,
	updated_at DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portfolio (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	entry_time DATE DEFAULT CURRENT_DATE,
	investments JSON NOT NULL,
	balance INTEGER DEFAULT 0,
	created_at DEFAULT CURRENT_TIMESTAMP,
	updated_at DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_entry_time ON portfolio(entry_time DESC);
